/**
 * Canonical numeric filter parameter definitions.
 *
 * This module is the single source of truth for numeric filter param names
 * and their UI group assignments. Both parseBuildQuery (build-state.ts) and
 * the metric column / filter-group rendering (build-view.ts) derive from here.
 *
 * Adding a new numeric filter requires adding its param name to the list
 * and an entry in FILTER_GROUPS — no other manual registration needed.
 */

// ---------------------------------------------------------------------------
// Flat list of all recognized numeric filter query param names
// ---------------------------------------------------------------------------

export const NUMERIC_FILTER_PARAM_NAMES = [
  // Case
  "case-max-volume-l",
  "case-max-length-mm",
  "case-max-width-mm",
  "case-max-height-mm",
  "case-max-weight-kg",
  "case-max-footprint-cm2",
  "case-max-gpu-length-mm",
  "case-max-gpu-width-mm",
  "case-max-gpu-thickness-mm",
  "case-max-pcie-slots",
  "case-max-lp-pcie-slots",
  "case-max-cpu-cooler-height-mm",
  "case-max-drive-25",
  "case-max-drive-35",
  "case-max-drive-525",
  "case-max-fan-40",
  "case-max-fan-60",
  "case-max-fan-80",
  "case-max-fan-92",
  "case-max-fan-120",
  "case-max-fan-140",
  "case-max-fan-180",
  "case-max-fan-200",
  "case-max-usb-a20",
  "case-max-usb-a32",
  "case-max-usb-c",
  "case-max-cny",
  "case-max-usd",
  // GPU
  "max-gpu-length-mm",
  "max-gpu-width-mm",
  "max-gpu-thickness-mm",
  "max-gpu-slots",
  "max-gpu-boost-clock-mhz",
  "max-gpu-memory-speed-gbps",
  "max-gpu-tdp-w",
  "max-gpu-fan-count",
  "max-gpu-displayport-count",
  "max-gpu-hdmi-count",
  "max-gpu-usb-c-count",
  // CPU Cooler
  "cooler-max-length-mm",
  "cooler-max-width-mm",
  "cooler-max-height-mm",
  "cooler-max-weight-g",
  "cooler-max-heatpipes",
  "cooler-max-block-length-mm",
  "cooler-max-block-width-mm",
  "cooler-max-block-height-mm",
  "cooler-max-pump-speed-rpm",
  "cooler-max-tube-length-mm",
  "cooler-max-fan-thickness-mm",
  "cooler-max-total-thickness-mm",
  "cooler-max-tdp-w",
  "cooler-max-fan-size-mm",
  "cooler-max-fan-count",
  "cooler-max-fan-speed-rpm",
  "cooler-max-airflow-cfm",
  "cooler-max-static-pressure-mmh2o",
  "cooler-max-noise-dba",
  "cooler-max-ram-clearance-mm",
  // PSU
  "psu-max-wattage",
  "psu-max-ac-input-v",
  "psu-max-fan-size-mm",
  "psu-max-cable-24pin",
  "psu-max-cable-8pin-eps",
  "psu-max-cable-pcie-62",
  "psu-max-cable-sata",
  "psu-max-cable-peripheral",
  "psu-max-warranty-years",
  // Motherboard
  "mobo-max-height-mm",
  "mobo-max-width-mm",
  "mobo-max-pci-slots",
  "mobo-max-pcie-x1",
  "mobo-max-pcie-x4",
  "mobo-max-pcie-x8",
  "mobo-max-pcie-x16-count",
  "mobo-max-ram-slots",
  "mobo-max-ram-capacity-gb",
  "mobo-max-ram-speed-mbps",
  "mobo-max-m2-count",
  "mobo-max-sata-count",
  "mobo-max-usb-ports",
  "mobo-max-usb-a20",
  "mobo-max-usb-c20",
  "mobo-max-usb-a32g1",
  "mobo-max-usb-c32g1",
  "mobo-max-usb-a32g2",
  "mobo-max-usb-c32g2",
  "mobo-max-usb-c32g2x2",
  "mobo-max-usb4",
  "mobo-max-tb3",
  "mobo-max-tb4",
  "mobo-max-usb2-header",
  "mobo-max-usb32g1-header",
  "mobo-max-usbc-header",
  "mobo-max-lan-ports",
  "mobo-max-lan-speed-gbps",
  "mobo-max-wifi-speed-mbps",
  "mobo-max-jack-35",
  "mobo-max-dp",
  "mobo-max-hdmi",
  "mobo-max-dvi",
  "mobo-max-fan-pump-headers",
  "mobo-max-rgb-header",
  "mobo-max-argb-header",
  // RAM
  "ram-max-height-mm",
] as const satisfies readonly string[];

// ---------------------------------------------------------------------------
// UI filter group assignments (kind → paramKey → group label)
// ---------------------------------------------------------------------------

export const FILTER_GROUPS: Record<string, Record<string, string>> = {
  case: {
    "case-max-length-mm": "Dimensions",
    "case-max-width-mm": "Dimensions",
    "case-max-height-mm": "Dimensions",
    "case-max-volume-l": "Dimensions",
    "case-max-footprint-cm2": "Dimensions",
    "case-max-weight-kg": "Dimensions",
    "case-max-gpu-length-mm": "GPU fit",
    "case-max-gpu-width-mm": "GPU fit",
    "case-max-gpu-thickness-mm": "GPU fit",
    "case-max-pcie-slots": "GPU fit",
    "case-max-lp-pcie-slots": "GPU fit",
    "case-max-cpu-cooler-height-mm": "Cooling",
    "case-max-fan-40": "Cooling",
    "case-max-fan-60": "Cooling",
    "case-max-fan-80": "Cooling",
    "case-max-fan-92": "Cooling",
    "case-max-fan-120": "Cooling",
    "case-max-fan-140": "Cooling",
    "case-max-fan-180": "Cooling",
    "case-max-fan-200": "Cooling",
    "case-max-usb-a20": "I/O & Price",
    "case-max-usb-a32": "I/O & Price",
    "case-max-usb-c": "I/O & Price",
    "case-max-cny": "I/O & Price",
    "case-max-usd": "I/O & Price",
  },
  gpu: {
    "max-gpu-length-mm": "Dimensions",
    "max-gpu-width-mm": "Dimensions",
    "max-gpu-thickness-mm": "Dimensions",
    "max-gpu-slots": "Dimensions",
    "max-gpu-boost-clock-mhz": "Power & Clocks",
    "max-gpu-memory-speed-gbps": "Power & Clocks",
    "max-gpu-tdp-w": "Power & Clocks",
    "max-gpu-fan-count": "Outputs & Fans",
    "max-gpu-displayport-count": "Outputs & Fans",
    "max-gpu-hdmi-count": "Outputs & Fans",
    "max-gpu-usb-c-count": "Outputs & Fans",
  },
  "cpu-cooler": {
    "cooler-max-length-mm": "Dimensions",
    "cooler-max-width-mm": "Dimensions",
    "cooler-max-height-mm": "Dimensions",
    "cooler-max-weight-g": "Dimensions",
    "cooler-max-block-length-mm": "Dimensions",
    "cooler-max-block-width-mm": "Dimensions",
    "cooler-max-block-height-mm": "Dimensions",
    "cooler-max-tube-length-mm": "Dimensions",
    "cooler-max-fan-thickness-mm": "Dimensions",
    "cooler-max-total-thickness-mm": "Dimensions",
    "cooler-max-fan-size-mm": "Dimensions",
    "cooler-max-ram-clearance-mm": "Dimensions",
    "cooler-max-heatpipes": "Performance",
    "cooler-max-pump-speed-rpm": "Performance",
    "cooler-max-tdp-w": "Performance",
    "cooler-max-fan-count": "Performance",
    "cooler-max-fan-speed-rpm": "Performance",
    "cooler-max-airflow-cfm": "Performance",
    "cooler-max-static-pressure-mmh2o": "Performance",
    "cooler-max-noise-dba": "Performance",
  },
  psu: {
    "psu-max-wattage": "Power",
    "psu-max-ac-input-v": "Power",
    "psu-max-cable-24pin": "Cables",
    "psu-max-cable-8pin-eps": "Cables",
    "psu-max-cable-pcie-62": "Cables",
    "psu-max-cable-sata": "Cables",
    "psu-max-cable-peripheral": "Cables",
    "psu-max-fan-size-mm": "Physical",
    "psu-max-warranty-years": "Physical",
  },
  motherboard: {
    "mobo-max-height-mm": "Dimensions",
    "mobo-max-width-mm": "Dimensions",
    "mobo-max-pci-slots": "Expansion",
    "mobo-max-pcie-x1": "Expansion",
    "mobo-max-pcie-x4": "Expansion",
    "mobo-max-pcie-x8": "Expansion",
    "mobo-max-pcie-x16-count": "Expansion",
    "mobo-max-ram-slots": "Memory & Storage",
    "mobo-max-ram-capacity-gb": "Memory & Storage",
    "mobo-max-ram-speed-mbps": "Memory & Storage",
    "mobo-max-m2-count": "Memory & Storage",
    "mobo-max-sata-count": "Memory & Storage",
    "mobo-max-usb-ports": "I/O",
    "mobo-max-usb-a20": "I/O",
    "mobo-max-usb-c20": "I/O",
    "mobo-max-usb-a32g1": "I/O",
    "mobo-max-usb-c32g1": "I/O",
    "mobo-max-usb-a32g2": "I/O",
    "mobo-max-usb-c32g2": "I/O",
    "mobo-max-usb-c32g2x2": "I/O",
    "mobo-max-usb4": "I/O",
    "mobo-max-tb3": "I/O",
    "mobo-max-tb4": "I/O",
    "mobo-max-usb2-header": "I/O",
    "mobo-max-usb32g1-header": "I/O",
    "mobo-max-usbc-header": "I/O",
    "mobo-max-lan-ports": "I/O",
    "mobo-max-lan-speed-gbps": "I/O",
    "mobo-max-wifi-speed-mbps": "I/O",
    "mobo-max-jack-35": "I/O",
    "mobo-max-dp": "I/O",
    "mobo-max-hdmi": "I/O",
    "mobo-max-dvi": "I/O",
    "mobo-max-fan-pump-headers": "I/O",
    "mobo-max-rgb-header": "I/O",
    "mobo-max-argb-header": "I/O",
  },
  ram: {
    "ram-max-height-mm": "Dimensions",
  },
};
